name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Formatting
        run: cargo fmt --check
      - name: Clippy (default)
        run: cargo clippy --all-targets
      - name: Clippy (forward feature)
        run: cargo clippy --all-targets --features forward
      - name: Test (default)
        run: cargo test --verbose
      - name: Test (forward feature)
        run: cargo test --features forward --verbose
